version: '3.8'
services:
  bot:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
      - ./airdrop.db:/app/airdrop.db
      - ./logs:/app/logs
      - ./users.xlsx:/app/users.xlsx
    restart: unless-stopped
    depends_on:
      - redis
  redis:
    image: redis:7.0
    restart: unless-stopped
    ports:
      - "6379:6379"